.github / workflow: Add workflow_dispatch trigger and feature for github page deploy
nolebase/nolebase pull request #39
Opened 2024-03-05 20:12 UTC by Nyovelt

2024-03-06 00:50 UTC, nekomeowww commented
Should GitHuh Pages be opt-in?

2024-03-06 17:05 UTC, Nyovelt commented on .github/workflows/production-deployment-to-github-pages.yaml
> +      url: https://nolebase.ayaka.io
It depends on your github pages settings. By default, yes.

2024-03-07 05:24 UTC, nekomeowww requested changes

2024-03-07 05:24 UTC, nekomeowww commented on .github/workflows/production-deployment-to-github-pages.yaml
> +      name: 正式 Production
名字也得改一下

```suggestion
      name: 正式 Production - GitHub Pages
```

2024-03-07 05:24 UTC, nekomeowww approved these changes

2024-03-07 05:29 UTC, merged